#!/bin/sh

APP_ID=b1ae09b2-5311-432e-b69c-65cb354f3472

curl -X POST "https://onesignal.com/api/v1/notifications" \
   -H "Content-Type: application/json; charset=utf-8" \
   -H "Authorization: Basic $OS_REST_API_KEY" \
   -d '{
       "app_id": $APP_ID,
       "collapse_id": "13",
       "include_aliases": {
            "external_id": ["will_test"]
        },
        "target_channel": "push",
       "contents": {"en": "Download Started"},
       "headings": {"en": "Download Progress"},
       "data": {
            "live_notification": {
                "key": "progress",
                "event": "start",
                "immutable_attributes": {},
                "initial_attributes": {},
                "event_updates": {
                    "current_progress": 60
                }
            }
        }
   }'
